- name: Node - Install Nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  tags:
    - languages
    - node
- name: Golang
  shell: rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.1.darwin-amd64.tar.gz
  become: true
  tags:
    - languages
    - golang
- name: Rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  tags:
    - languages
    - rust
