- name: Golang
  shell: rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz
  become: true
  tags:
    - languages
    - golang
- name: Rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  tags:
    - languages
    - rust
- name: Node - Install Nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  tags:
    - languages
    - node
- name: Node - Install LTS
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install lts/*'
  args:
    creates: '{{ ansible_env.HOME }}/.nvm/versions/node'
    chdir: '{{ ansible_env.HOME }}'
    executable: /bin/bash
  tags:
    - languages
    - node
