- name: AWS CLI
  become: true
  shell: |
    curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
    sudo installer -pkg AWSCLIV2.pkg -target /
  tags:
    - tooling
    - aws
- name: stow
  become: true
  shell: |
    brew install stow
  tags:
    - tooling
    - stow
- name: tmux
  become: true
  shell: |
    brew install tmux
  tags:
    - tooling
    - tmux
