- name: Docker Dependencies
  become: true
  apt:
    name: ['ca-certificates', 'gnupg', 'lsb-release']
  tags:
    - install
    - dependencies
    - docker
- name: Docker
  become: true
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
  tags:
    - tooling
    - docker
- name: Docker-Compose
  become: true
  shell: |
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  tags:
    - tooling
    - docker-compose
- name: AWS CLI
  become: true
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  tags:
    - tooling
    - aws
